name: Publish Langium Extension

on:
  push:
    branches:
      - main
      - developing
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build project
      - name: Build project
        run: |
          npm run langium:generate
          npm run build

      # Cache Node.js modules and npm cache for faster builds
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Patch version
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@bot.com"
          npm version patch --no-git-tag-version
          git add package.json
          git add package-lock.json
          git commit -m "chore(package.json/package-lock.json): bump version [skip ci]"
          git push

      # Install vsce (VS Code Extension Manager)
      - name: Install vsce
        run: npm install -g @vscode/vsce

      # Publish extension based on the branch
      - name: Publish to VSCode Marketplace
        run: |
          npm ci --omit=dev
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            vsce publish --pat ${{ secrets.VSCODE_TOKEN }}
          elif [[ "${{ github.ref }}" == "refs/heads/developing" ]]; then
            vsce publish --pre-release --pat ${{ secrets.VSCODE_TOKEN }}
          else
            echo "Branch is neither main nor developing, skipping publish."
          fi
